# Generated by Django 4.2 on 2024-11-12 06:29

import babelbase.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namespace",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Unique Namespace Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Namespace",
                "verbose_name_plural": "Namespaces",
                "ordering": ("-namespace",),
            },
        ),
        migrations.CreateModel(
            name="TranslationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "identifier",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        verbose_name="Identifier Slug",
                    ),
                ),
                ("_lang", models.CharField(max_length=7, verbose_name="Language Code")),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Content Source"),
                ),
                (
                    "changed",
                    models.BooleanField(default=True, verbose_name="Has changed"),
                ),
                (
                    "not_used",
                    models.BooleanField(default=False, verbose_name="Not in use"),
                ),
                (
                    "complete",
                    models.BooleanField(
                        default=False, verbose_name="Complete Translation"
                    ),
                ),
                (
                    "template_registry",
                    models.JSONField(
                        blank=True,
                        default=babelbase.utils.default_json_list,
                        verbose_name="Appearances in Templates",
                    ),
                ),
                (
                    "duplicates_registry",
                    models.JSONField(
                        blank=True,
                        default=babelbase.utils.default_json_list,
                        verbose_name="Potential Duplicate Sources",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_source_qs",
                        to="babelbase.namespace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Source",
                "verbose_name_plural": "Translation Sources",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="TranslationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("_lang", models.CharField(max_length=7, verbose_name="Language Code")),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Content Translation"),
                ),
                (
                    "translated",
                    models.BooleanField(default=False, verbose_name="Is translated"),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, verbose_name="Translation approved"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_target_qs",
                        to="babelbase.translationsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Target",
                "verbose_name_plural": "Translation Targets",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="translationtarget",
            constraint=models.UniqueConstraint(
                fields=("source", "_lang"), name="source-lang-constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="translationsource",
            constraint=models.UniqueConstraint(
                fields=("namespace", "identifier"),
                name="namespace-identifier-constraint",
            ),
        ),
    ]
